apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: dayasahu6077/configserver:v26dec
          ports:
            - containerPort: 8071
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: native
            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
              value: file:/config/employee
          volumeMounts:
            - name: employee-config
              mountPath: /config/employee
              readOnly: true
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8071
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8071
            initialDelaySeconds: 40
      volumes:
        - name: employee-config
          configMap:
            name: employee-config
