apiVersion: v1
kind: ConfigMap
metadata:
  name: configserver-files
data:
  employee.properties: |-
    spring.application.name=employee
    server.port=8080
    spring.application.instance_id=${spring.application.name}:${random.value}
    management.endpoints.web.base-path=/actuator
    management.endpoints.web.exposure.include=health,info,metrics,beans,conditions,mappings,env,loggers,threaddump,heapdump
    management.endpoint.health.show-details=always
    commonprop=test
    spring.cloud.config.fail-fast=true
    spring.cloud.config.retry.max-attempts=6
  employee-dev.properties: |-
    poc.environment.msg=this is employee updated dev environment 22 dec 2026
  employee-prod.properties: |-
    poc.environment.msg=this is employee prod environment 25 dec 2025
  department.properties: |-
    poc.environment.msg=this is department default environment 25 dec 2025
    spring.application.name=department
    server.port=8082
    spring.application.instance_id=${spring.application.name}:${random.value}
    management.endpoints.web.base-path=/actuator
    management.endpoints.web.exposure.include=health,info,metrics,beans,conditions,mappings,env,loggers,threaddump,heapdump
    management.endpoint.health.show-details=always
  department-dev.properties: |-
    poc.environment.msg=this is department dev environment 25 dec 2025
  department-prod.properties: |-
    poc.environment.msg=this is department prod environment 25 dec 2025

