apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: dayasahu6077/configserver:v26dec
          ports:
            - containerPort: 8071
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: native

            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
              value: file:///config/props/

            - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
              value: /actuator
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,info,metrics,beans,conditions,mappings,env,loggers,threaddump,heapdump
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: always

          volumeMounts:
            - name: config-volume
              mountPath: /config/props
              readOnly: true

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8071
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8071
            initialDelaySeconds: 40
            periodSeconds: 20

      volumes:
        - name: config-volume
          configMap:
            name: configserver-files
            items:
              - key: apigateway.properties
                path: props/employee/apigateway.properties
              - key: apigateway-dev.properties
                path: props/employee/apigateway-dev.properties
              - key: employee-prod.properties
                path: props/employee/employee-prod.properties
              - key: department.properties
                path: props/department/department.properties
              - key: department-dev.properties
                path: props/department/department-dev.properties
              - key: department-prod.properties
                path: props/department/department-prod.properties

---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
